spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb_db
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    properties:
      hibernate:
        format_sql: false



  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
          required: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secretKey: mysupersecretkeyihavetomakeitlongoriwillgetanexceptionfortooshortlmao
      jwtExpiration: 86400000 # 1 day

aws:
  s3:
    bucket-name: airbnb-media
    endpoint: http://s3:9000
    external-endpoint: http://localhost:9000
    access-key: "user"
    secret-key: "password"